pipeline {
    agent { label 'slave' }

    environment {
        REGISTRY = 'omarleon'
        URL_PRD = https://prd.omarleon.com 
        URL_DEV = https://dev.omarleon.com
    }
     
    stages {
        stage('Clone Repository') {
            steps {
                git(
                    url: 'https://github.com/leonomar8/ms-agosto-01.git',
                    branch: 'main',
                    credentialsId: 'github-token'
                )
            }
        }
                
        stage('Build with Maven') {
            steps {
                sh "mvn clean package -DskipTests"
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv('sonar') {
                        sh """
                        mvn clean verify sonar:sonar \
                          -Dsonar.projectKey=ms-agosto-01 \
                          -Dsonar.projectName=ms-agosto-01
                        """
                    }
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    def imageTag = "${REGISTRY}/ms-agosto-01:${BUILD_NUMBER}"

                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                        def customImage = docker.build(imageTag)
                        customImage.push()
                    }
                }
            }
        }                


        stage('Deploy') {
            steps {
                script {
                    // Set tag in docker-compose.yaml
                    dir('docker') {
                        def buildTag = env.BUILD_NUMBER
                        sh "sed -i 's|TAG|${buildTag}|g' docker-compose.yaml"
                        sh "cat docker-compose.yaml"
                        
                        // Set environment variables in docker-compose.yaml
                        def message = (env.BRANCH_NAME == 'main') ? env.URL_PRD : env.URL_DEV
                        sh "sed -i 's|\\(MESSAGE=\\).*|MESSAGE=${message}|g' docker-compose.yaml"
                        sh "cat docker-compose.yaml"
                        
                        // Run Docker Compose
                        sh "docker compose up -d"
                    }
                }
            }
        }


        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
    }
}